modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="growable_ores"
version="${forge_mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
credits = "Rafan,gilnet,All translators"


[[dependencies.growable_ores]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.growable_ores]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"